name: Deploy to Cloud Run

on:
  push:
    branches: [ "mainx" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        env:
          BUILD_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
          BUILD_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/$BUILD_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@$BUILD_PROJECT_ID.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        env:
          BUILD_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          gcloud run deploy $BUILD_PROJECT \
            --source . \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --allow-unauthenticated=false

